[env:firebeetle2_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
board = dfrobot_firebeetle2_esp32c6
framework = arduino
monitor_speed = 115200

board_upload.flash_size = 4MB
board_build.flash_size = 4MB
board_build.partitions = partitions.csv

build_flags =
    -DZIGBEE_MODE_ED=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_filters = esp32_exception_decoder